### ISSUE TITLE
Missing contributors profile in README.md

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/Interactive-Book#40]
#### I am submitting a -
* [] **Feature Request**

#### Describe your bug/feature -
The contributors profile can be added to the README page.

**Comment by satu0king** [comment]
Additionally an about/contributors page should be added to the website itself

**Comment by deepak2431** [comment]
@satu0king Yeah, that would be a great idea. To add a contributors profile in the README page can be added as a GCI task under easy I think so. For adding it to the website the design needs to be finalised first.

**Comment by JoshHeng** [comment]
Task claimed

**Comment by JoshHeng** [comment]
Does the contributers page need to be live?

If so, how should we do it?
- CircuitVerse itself uses [Open Collective](https://opencollective.com/) to show contributers, however that is mainly a donation platform and we would need to set up a new account for the Interactive Book (which would need to be done by an admin)
[Preview](https://opencollective.com/CircuitVerse/contributors.svg?width=890&button=false)

- We could use https://contributors-img.firebaseapp.com which generates contributers from the GitHub [contributers](https://github.com/CircuitVerse/Interactive-Book/graphs/contributors) page, but this doesn't provide a hyperlink or profile names and only shows the top 100 people
[Preview](https://contributors-img.firebaseapp.com/image?repo=CircuitVerse/Interactive-Book)

- [All Contributers](https://github.com/all-contributors/all-contributors) could be an option but it is a GitHub bot which would need to be added by an admin, which would just update the README (and not the website itself)

Otherwise, we could simply provide a link to the [Contributers](https://github.com/CircuitVerse/Interactive-Book/graphs/contributors) GitHub page, but that doesn't show all of the contributors and doesn't look as good

**Comment by JoshHeng** [comment]
Or we could just provide a page for contributors to manually add themselves to

**Comment by fluctix** [comment]
I would prefer the second option ,
