### ISSUE TITLE
Broken Prev/Next navigation buttons with new just-the-doc theme and new structure (GSoD2020)

### ISSUE THREAD

**Issue by danielluehr** [CircuitVerse/Interactive-Book#476]
## Describe the bug

The new version of the book (being developed under the GSoD 2020 project) replaced the old version Just-the-docs (JTD) Jekyll theme, which was installed locally and included styling and structure hardcoded into it, with the current upstream JTD version installed as a Gem/plugin for Jekyll. The new version uses the JTD "pages with children" feature to organize the books in two levels: chapters (toplevel) and sections (second level within each chapter). When the JTD theme was upgraded to upstream the prev/next buttons liquid code started to misbehave, and when the whole new structure replaced the current one, the code failed and jekyll was unable to generate the site. I haven't had the opportunity to investigate the reason. It is currently commented out in the development branch (the code itself is in the file `_includes/prev_next.html` which is included in `_includes/content_header.html` )

## To Reproduce

Test the version in PR #474 

## Expected behavior

Navigation previous/next buttons should navigate through the structure of the book.

## Screenshots

![CVIB_prev_next-2020-10-07](https://user-images.githubusercontent.com/20018048/95384073-797f5e00-08c2-11eb-8a59-5d3dee8a3d32.png)

On the left is the current version, on the right is the new (GSoD2020) version.

## Additional context

The table of content for each chapter is generated automatically with the code in `_includes/chapter_toc.html` it might be useful for the prev/next buttons also.

**Comment by anushri20** [comment]
@danielluehr Hi, have you fixed this or still needs to be fixed?

**Comment by anushri20** [comment]
okay, I would like to give it a try !

**Comment by Shivansh2407** [comment]
Go ahead @anushri20 👍

**Comment by Vishal-raj-1** [comment]
is this issue fixed ? @anushri20 are you working on this issue ?

**Comment by anushri20** [comment]
@Vishal-raj-1 Hi, I am not working on this issue right now. You can work on this issue if you want to.

**Comment by SaDevat** [comment]
@danielluehr is this issue still valid? If yes can I start with it?

**Comment by manjotsidhu** [comment]
@danielluehr This issue is due to the ordering of pages according to `nav_order` and since now that you have made it to adjust level and section both inside a single variable, ordering of those will be a hard task. Instead I would suggest to actually use `level` and `nav_order` separately. This will make using variables easy and more modular to handle them.

From :
`nav_order: l0s001`

To :
`level: 0`
`nav_order: 1`

I am still figuring out why we decided to go with a single variable rather than keeping it modular and single responsibility for each variable as practiced in SOLID principles.

@Shivansh2407 @tachyons

**Comment by manjotsidhu** [comment]
@danielluehr This issue is being caused due to the new navigation structure of `nav_order`. `nav_order` should have the order of a page in sequential order just like we had previously. But now, `level` is included and `section` order is added to `nav_order`. I don't understand why only one variable was made to accumulate these all parameters. 

This makes the ordering hard and code less modular, fails single responsibility principle greatly. It would be always better to go for more variables than making a pattern of a `nav_order`.

Moreover, the sequential order of a page is not even present since only section (relative index from the section to the page) and level are there. I can't imagine how the navigation from JTD is getting ordered because in their documentation they clearly defined how the structure should be.

https://pmarsceill.github.io/just-the-docs/docs/navigation-structure/

@Shivansh2407 @tachyons

**Comment by manjotsidhu** [comment]
@Shivansh2407 kindly close this, #511 merged

**Comment by Shivansh2407** [comment]
Closing this Issue, Fixed in #511
