### ISSUE TITLE
Add a button to each section to copy link to the section

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/Interactive-Book#91]
**New Feature**
The Interactive-Book comprises of various sections and adding a button to copy a link will help in sharing a specific section.

Something like this [link](https://developers.google.com/open-source/gci/resources/getting-started#4_easy_steps)

Links can be added to each and every section or to some specific types of content.

**Are you working on this issue?**
Nope. For GCI 2019

**Comment by JoshHeng** [comment]
What links are we referring to? 
- The top, horizontal blue navigation bar
- The left navigation list
- The right page contents navigation list
- Various inline links

**Comment by JoshHeng** [comment]
Or is this the shareable link that appears when a header is hovered over?

**Comment by YashKumarVerma** [comment]
There is an issue here, both #152 and #155 provide the same functionality, links to sections.

But, since
#152 
- has single commit
- has less files edited
- was opened before
- changes the cursor to a pointer  

whereas in #155 

- has multiple commits
- has more files edited
- was opened later
- changes the cursor to text type
- included jquery as a library

therefore keeping the conventions and good practices in mind, #152 is being merged and #155 is closed its favor.

Thanking @JoshHeng  and @junron  for their contribution.
